export default interface ScheduleModel {
    SAS_SCHEDULE_ID: string
    WC_CLIENTE_COD: string
    SAS_EQUIPE_ID: string
    SAS_SCHEDULE_HRFIM: string
    SAS_SCHEDULE_HRINICIO: string
    SAS_SCHEDULE_DATA: string
    SAS_SCHEDULE_STATUS: string
    SAS_SCHEDULE_OBSERVA: string
    SAS_CLI_NOME_COMPLETO?: string
    SAS_EQUIPE_INICIAL_ID: any
    WC_PRODUTO_COD: string
    SAS_SINALIZADOR: string
    SAS_PROP_ID: string
    WF_OPORTUNI_ID: string
    SAS_SCHEDULE_START_DATE?: string
    SAS_SCHEDULE_END_DATE?: string
    SAS_SCHEDULE_EVERY?: string
    SAS_SCHEDULE_FREQUENCY?: string
    SAS_SCHEDULE_WEEK_DAY?: string
    SAS_SERVICE_NOME?: string
    COD_USUARIO?: string
    SAS_SCHEDULE_INICIO_SERV?: string
    SAS_SCHEDULE_FIM_SERV?: string
    SAS_SCHEDULE_LOCG_INI?: string
    SAS_SCHEDULE_LOCG_FIM?: string
    SAS_SCHEDULE_CHKOUT_COM?: string
    SAS_SCHEDULE_CHKOUT_COM_TEXT?: string
    SAS_SCHEDULE_HORA_CHK_INF?: string
    SAS_SCHEDULE_HORA_CHO_IN?: string
    SAS_SCHEDULE_UPDATEAT?: string
    SAS_SCHEDULE_UPDATEDAT?: string
    SAS_SCHEDULE_CREATEDAT?: string
    SAS_SCHEDULE_REC_ID?: string
    SAS_SCHEDULE_GROUP?: string
    SAS_SCHEDULE_SERVICES?: Array<any>
}